branch-defaults:
  master:
    environment: node-express-env
    group_suffix: null
global:
  application_name: scpapi
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-2
  profile: eb-cli
  sc: git
